version: '3.7'
services:
  app:
    build: .
    tty: true
    ports:
      - 3005:3005
      - 5555:5555
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgresql://fffk10:postgres@db:5432/postgres
    networks:
      - app-net
    depends_on:
      - db
  db:
    build:
      context: '.'
      dockerfile: 'db.Dockerfile'
    env_file:
      - .env
    restart: always
    ports:
      - 5434:5432
    volumes:
      - ./db/postgres/init.d:/docker-entrypoint-initdb.d
      - ./db/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
    networks:
      - app-net

networks:
  app-net:
    driver: bridge